/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Musica;

/**
 *
 * @author jochechavez
 */
public class reproductor extends javax.swing.JFrame {
    sonido son;
    /**
     * Creates new form reproductor
     */
    public reproductor() {
        initComponents();
        jbtreproducir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtreproducir = new javax.swing.JButton();
        jlbnombreCancion = new javax.swing.JLabel();
        jbtpause = new javax.swing.JButton();
        jbtstop = new javax.swing.JButton();
        jlbactualframe = new javax.swing.JLabel();
        jsliderCancion = new javax.swing.JSlider();
        jlbduracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reproductor de Musica");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reproductor de Musica");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cover.png"))); // NOI18N

        jbtreproducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play2.png"))); // NOI18N
        jbtreproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtreproducirActionPerformed(evt);
            }
        });

        jlbnombreCancion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbnombreCancion.setText("Nombre Cancion: ");

        jbtpause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pause2.png"))); // NOI18N
        jbtpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpauseActionPerformed(evt);
            }
        });

        jbtstop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop2.png"))); // NOI18N
        jbtstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtstopActionPerformed(evt);
            }
        });

        jlbactualframe.setText("0 min");

        jlbduracion.setText("0 min");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtreproducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtpause, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtstop, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbnombreCancion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbactualframe)
                                .addGap(18, 18, 18)
                                .addComponent(jsliderCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbduracion)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtstop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jlbnombreCancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbactualframe)
                            .addComponent(jlbduracion)
                            .addComponent(jsliderCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtreproducir)
                            .addComponent(jbtpause, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtreproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtreproducirActionPerformed
        son.reproducir();
        jbtreproducir.setEnabled(false);
        jbtpause.setEnabled(true);
    }//GEN-LAST:event_jbtreproducirActionPerformed

    private void jbtpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpauseActionPerformed
        son.pausar();
        jbtreproducir.setEnabled(true);
        jbtpause.setEnabled(false);
    }//GEN-LAST:event_jbtpauseActionPerformed

    private void jbtstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtstopActionPerformed
        son.detener();
        jbtreproducir.setEnabled(false);
        jbtpause.setEnabled(false);
        jbtstop.setEnabled(false);
    }//GEN-LAST:event_jbtstopActionPerformed

    /**
     *
     * @return
     */
    public javax.swing.JSlider getJslider(){
        return jsliderCancion;
    }

    /**
     *
     * @param nombre
     */
    public void setNombre(String nombre){
        jlbnombreCancion.setText("Canción: "+nombre);
    }

    /**
     *
     * @return
     */
    public javax.swing.JLabel getJlbDuracion(){
        return jlbduracion;
    }

    /**
     *
     * @return
     */
    public javax.swing.JLabel getJlbFrame(){
        return jlbactualframe;
    }

    /**
     *
     * @param son
     */
    public void setSonido(sonido son){
        this.son = son;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtpause;
    private javax.swing.JButton jbtreproducir;
    private javax.swing.JButton jbtstop;
    private javax.swing.JLabel jlbactualframe;
    private javax.swing.JLabel jlbduracion;
    private javax.swing.JLabel jlbnombreCancion;
    private javax.swing.JSlider jsliderCancion;
    // End of variables declaration//GEN-END:variables
}
